services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # MAKERS
  NaeSymfonyBundles\NaeRestBundle\Maker\MakeRest:
    arguments: ['@maker.doctrine_helper']
    tags:
      - { name: maker.command }
  NaeSymfonyBundles\NaeRestBundle\Maker\MakeAuthRest:
    arguments: [ '@maker.doctrine_helper' ]
    tags:
      - { name: maker.command }

  # Helpers
  NaeSymfonyBundles\NaeRestBundle\Service\NaeRestAuthService:
    arguments: []